### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by david0315** [caohao-php/ycdatabase#1]
安装环境：
uname -a
Linux 10-23-143-131 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

php -v
PHP 7.2.13 (cli) (built: Dec 26 2018 19:08:22) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

 /usr/local/php7/bin/phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718

[ycdatabase_extension]# ./configure --help
-bash: ./configure: Permission denied
[ycdatabase_extension]# sudo ./configure --help
sudo: ./configure: command not found

**Comment by caohao-go** [comment]
你需要添加 可执行权限，  chmod +x  ./configure   ，然后再执行后续操作

**Comment by caohao-go** [comment]
$cd ~/ycdatabase/ycdatabase_extension
$/path/to/phpize
$chmod +x ./configure
$./configure --with-php-config=/path/to/php-config
$make
$make install

**Comment by david0315** [comment]
好的，非常感谢
