### ISSUE TITLE
扩展无法运行

### ISSUE THREAD

**Issue by Eno-CN** [caohao-php/ycdatabase#4]
PHP版本7.4.6 求大佬解答
# php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zlib

[Zend Modules]

**Comment by caohao-go** [comment]
php 7.4 好像是有点问题，等我看看！

**Comment by caohao-go** [comment]
> PHP版本7.4.6 求大佬解答
> 
> # php -m
> PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> [PHP Modules]
> bcmath
> Core
> ctype
> curl
> date
> dom
> fileinfo
> filter
> gettext
> hash
> iconv
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_sqlite
> Phar
> posix
> Reflection
> session
> shmop
> SimpleXML
> soap
> sockets
> SPL
> sqlite3
> standard
> sysvsem
> tokenizer
> xml
> xmlreader
> xmlrpc
> xmlwriter
> xsl
> zlib
> 
> [Zend Modules]

你先试下在 php 7.3 下看行不行

**Comment by caohao-go** [comment]
> PHP版本7.4.6 求大佬解答
> 
> # php -m
> PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> [PHP Modules]
> bcmath
> Core
> ctype
> curl
> date
> dom
> fileinfo
> filter
> gettext
> hash
> iconv
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_sqlite
> Phar
> posix
> Reflection
> session
> shmop
> SimpleXML
> soap
> sockets
> SPL
> sqlite3
> standard
> sysvsem
> tokenizer
> xml
> xmlreader
> xmlrpc
> xmlwriter
> xsl
> zlib
> 
> [Zend Modules]


> PHP版本7.4.6 求大佬解答
> 
> # php -m
> PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> [PHP Modules]
> bcmath
> Core
> ctype
> curl
> date
> dom
> fileinfo
> filter
> gettext
> hash
> iconv
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_sqlite
> Phar
> posix
> Reflection
> session
> shmop
> SimpleXML
> soap
> sockets
> SPL
> sqlite3
> standard
> sysvsem
> tokenizer
> xml
> xmlreader
> xmlrpc
> xmlwriter
> xsl
> zlib
> 
> [Zend Modules]

你再重新下载再安装试试

**Comment by Eno-CN** [comment]
> > PHP版本7.4.6 求大佬解答
> > # php -m
> > PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> > [PHP Modules]
> > bcmath
> > Core
> > ctype
> > curl
> > date
> > dom
> > fileinfo
> > filter
> > gettext
> > hash
> > iconv
> > json
> > libxml
> > mbstring
> > mysqli
> > mysqlnd
> > openssl
> > pcntl
> > pcre
> > PDO
> > pdo_mysql
> > pdo_sqlite
> > Phar
> > posix
> > Reflection
> > session
> > shmop
> > SimpleXML
> > soap
> > sockets
> > SPL
> > sqlite3
> > standard
> > sysvsem
> > tokenizer
> > xml
> > xmlreader
> > xmlrpc
> > xmlwriter
> > xsl
> > zlib
> > [Zend Modules]
> 
> 你先试下在 php 7.3 下看行不行

昨天我用PHP7.3是成功的。

**Comment by Eno-CN** [comment]
> > PHP版本7.4.6 求大佬解答
> > # php -m
> > PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> > [PHP Modules]
> > bcmath
> > Core
> > ctype
> > curl
> > date
> > dom
> > fileinfo
> > filter
> > gettext
> > hash
> > iconv
> > json
> > libxml
> > mbstring
> > mysqli
> > mysqlnd
> > openssl
> > pcntl
> > pcre
> > PDO
> > pdo_mysql
> > pdo_sqlite
> > Phar
> > posix
> > Reflection
> > session
> > shmop
> > SimpleXML
> > soap
> > sockets
> > SPL
> > sqlite3
> > standard
> > sysvsem
> > tokenizer
> > xml
> > xmlreader
> > xmlrpc
> > xmlwriter
> > xsl
> > zlib
> > [Zend Modules]
> 
> > PHP版本7.4.6 求大佬解答
> > # php -m
> > PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> > [PHP Modules]
> > bcmath
> > Core
> > ctype
> > curl
> > date
> > dom
> > fileinfo
> > filter
> > gettext
> > hash
> > iconv
> > json
> > libxml
> > mbstring
> > mysqli
> > mysqlnd
> > openssl
> > pcntl
> > pcre
> > PDO
> > pdo_mysql
> > pdo_sqlite
> > Phar
> > posix
> > Reflection
> > session
> > shmop
> > SimpleXML
> > soap
> > sockets
> > SPL
> > sqlite3
> > standard
> > sysvsem
> > tokenizer
> > xml
> > xmlreader
> > xmlrpc
> > xmlwriter
> > xsl
> > zlib
> > [Zend Modules]
> 
> 你再重新下载再安装试试

PHP7.4.6编译后报错
```
/src/ycdatabase/ycdatabase_extension/src/string.c:60:2: error: too many arguments to function ‘php_pcre_match_impl’
   60 |  php_pcre_match_impl(pce, subject_str, strlen(subject_str), &retval, matches, 0, 0, Z_L(0), Z_L(0));
      |  ^~~~~~~~~~~~~~~~~~~
```

**Comment by Eno-CN** [comment]
> > PHP版本7.4.6 求大佬解答
> > # php -m
> > PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> > [PHP Modules]
> > bcmath
> > Core
> > ctype
> > curl
> > date
> > dom
> > fileinfo
> > filter
> > gettext
> > hash
> > iconv
> > json
> > libxml
> > mbstring
> > mysqli
> > mysqlnd
> > openssl
> > pcntl
> > pcre
> > PDO
> > pdo_mysql
> > pdo_sqlite
> > Phar
> > posix
> > Reflection
> > session
> > shmop
> > SimpleXML
> > soap
> > sockets
> > SPL
> > sqlite3
> > standard
> > sysvsem
> > tokenizer
> > xml
> > xmlreader
> > xmlrpc
> > xmlwriter
> > xsl
> > zlib
> > [Zend Modules]
> 
> > PHP版本7.4.6 求大佬解答
> > # php -m
> > PHP Warning: PHP Startup: Unable to load dynamic library 'ycdatabase' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase: cannot open shared object file: No such file or directory), **/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/ycdatabase.so: undefined symbol: _zval_ptr_dtor)) in Unknown on line 0**
> > [PHP Modules]
> > bcmath
> > Core
> > ctype
> > curl
> > date
> > dom
> > fileinfo
> > filter
> > gettext
> > hash
> > iconv
> > json
> > libxml
> > mbstring
> > mysqli
> > mysqlnd
> > openssl
> > pcntl
> > pcre
> > PDO
> > pdo_mysql
> > pdo_sqlite
> > Phar
> > posix
> > Reflection
> > session
> > shmop
> > SimpleXML
> > soap
> > sockets
> > SPL
> > sqlite3
> > standard
> > sysvsem
> > tokenizer
> > xml
> > xmlreader
> > xmlrpc
> > xmlwriter
> > xsl
> > zlib
> > [Zend Modules]
> 
> 你再重新下载再安装试试

OK PHP7.4.6编译通过了。
